services:
  - type: web
    name: truequetools-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn truequetools.wsgi:application --bind 0.0.0.0:8000"
    plan: free
    regions:
      - oregon
